// Data Source
const taishinPlans = [
  {
    id: "taishin_chill_party",
    name: "Chill刷-瘋聚會-歡聚微醺",
    rate: "10%",
    merchants: [
      "詹記麻辣火鍋",
      "萬客什鍋",
      "海底撈",
      "屋馬燒肉",
      "屋馬",
      "茶六燒肉堂",
      "茶六",
      "新村站著吃",
      "燒肉政宗",
      "碳佐麻里",
      "雞湯大叔",
      "gonna共樂遊",
      "BRUN 不然",
      "CAFE ACME",
      "The Antipodean",
      "貳樓",
      "樂子 the Diner",
      "Fake Sober",
      "Draft Land",
      "臺虎精釀",
      "臺虎精釀啜飲室",
      "ABV系列",
      "Bar TCRC",
      "Bar Home",
      "Phowa",
      "MOONROCK",
    ],
    instruction:
      "活動期間 2026/7/8-2026/9/30。瘋聚會-歡聚微醺，含火鍋燒肉、餐酒館與酒吧，需使用實體卡或指定電子支付。",
    icon: "fa-fire",
    bank: "Taishin",
  },
  {
    id: "taishin_chill_drink",
    name: "Chill刷-瘋聚會-日常續命",
    rate: "10%",
    merchants: [
      "50嵐",
      "得正",
      "八曜和茶",
      "五桐號",
      "龜記",
      "茶之魔手",
      "UG TEA",
      "叮哥茶飲",
      "CAFE!N",
      "%Arabica",
      "COMPOSE COFFEE",
    ],
    instruction:
      "活動期間 2026/7/8-2026/9/30。瘋聚會-日常續命，限指定連鎖飲料店，需使用實體卡或指定電子支付。",
    icon: "fa-mug-hot",
    bank: "Taishin",
  },
  {
    id: "taishin_chill_date",
    name: "Chill刷-瘋聚會-約會犒賞",
    rate: "5%",
    merchants: ["饗饗 INPARADISE", "饗饗", "INPARADISE", "NAGOMI"],
    instruction:
      "活動期間 2026/7/8-2026/9/30。瘋聚會-約會犒賞，需使用實體卡或指定電子支付。",
    icon: "fa-utensils",
    bank: "Taishin",
  },
  {
    id: "taishin_chill_star",
    name: "Chill刷-沉浸娛樂-應援追星",
    rate: "5%",
    merchants: [
      "WEVERSE",
      "K-MONSTAR",
      "微樂客",
      "五大唱片",
      "仙女樹",
      "FANME",
      "NOL",
    ],
    instruction:
      "活動期間 2026/7/8-2026/9/30。沉浸娛樂-應援追星，需使用實體卡或指定電子支付。",
    icon: "fa-star",
    bank: "Taishin",
  },
  {
    id: "taishin_chill_streaming",
    name: "Chill刷-沉浸娛樂-熬夜追更",
    rate: "5%",
    merchants: [
      "巴哈姆特",
      "BOOK WALKER",
      "Animate",
      "樂天KOBO",
      "Readmoo讀墨",
      "Netflix",
      "Disney+",
      "愛爾達",
    ],
    instruction:
      "活動期間 2026/7/8-2026/9/30。沉浸娛樂-熬夜追更，需使用實體卡或指定電子支付。",
    icon: "fa-tv",
    bank: "Taishin",
  },
  {
    id: "taishin_chill_digital_gadget",
    name: "Chill刷-沉浸娛樂-數位外掛",
    rate: "3.3%",
    merchants: [
      "Apple 直營",
      "Apple官網",
      "Studio A",
      "DJI",
      "Insta360",
      "GoPro",
      "蝦皮",
      "淘寶",
      "酷澎",
      "Uber Eats",
    ],
    instruction:
      "活動期間 2026/7/8-2026/9/30。沉浸娛樂-數位外掛，需使用實體卡或指定電子支付。",
    icon: "fa-laptop-code",
    bank: "Taishin",
  },
  {
    id: "taishin_chill_nutrition",
    name: "Chill刷-獨自升級-營養補給",
    rate: "5%",
    merchants: [
      "好好生醫",
      "好在乎",
      "營養師輕食",
      "VITABOX",
      "MYPROTEIN",
      "UrMart優馬選品",
    ],
    instruction:
      "活動期間 2026/7/8-2026/9/30。獨自升級-營養補給，需使用實體卡或指定電子支付。",
    icon: "fa-capsules",
    bank: "Taishin",
  },
  {
    id: "taishin_chill_fitness",
    name: "Chill刷-獨自升級-體態養成",
    rate: "5%",
    merchants: [
      "Anytime Fitness",
      "健身工廠",
      "World Gym",
      "超核心",
      "超核心 Hypercore",
      "KX PILATES",
      "虎鐵健身",
      "虎鐵健身 X 器械皮拉提斯",
      "17FIT",
    ],
    instruction:
      "活動期間 2026/7/8-2026/9/30。獨自升級-體態養成，需使用實體卡或指定電子支付。",
    icon: "fa-dumbbell",
    bank: "Taishin",
  },
  {
    id: "taishin_chill_sportsbrand",
    name: "Chill刷-獨自升級-運動品牌",
    rate: "5%",
    merchants: [
      "Adidas",
      "New Balance",
      "PUMA",
      "Onitsuka Tiger",
      "Nike",
      "HOKA",
      "Salomon",
      "lululemon",
    ],
    instruction:
      "活動期間 2026/7/8-2026/9/30。獨自升級-運動品牌，需使用實體卡或指定電子支付。",
    icon: "fa-shirt",
    bank: "Taishin",
  },
  {
    id: "taishin_pay_app",
    name: "Pay著刷-台新Pay",
    rate: "3.8%",
    merchants: [
      "台新Pay",
      "全家",
      "7-11",
      "新光三越",
      "Richart Mart",
      "康是美",
      "IKEA",
      "NET",
    ],
    instruction:
      "台新Pay及台新Pay+綁定支付享3.8%回饋，完整店家詳見台新Pay官網。",
    icon: "fa-mobile-screen",
    bank: "Taishin",
  },
  {
    id: "taishin_pay_taiwan",
    name: "Pay著刷-台新Pay(TWQR/台灣Pay)",
    rate: "3.8%",
    merchants: ["神腦", "燦坤", "全國電子", "麥當勞", "美廉社", "大樹藥局"],
    instruction:
      "限使用台新Pay(TWQR、台灣Pay)綁定支付，完整店家詳見台灣Pay場域。",
    icon: "fa-qrcode",
    bank: "Taishin",
  },
  {
    id: "taishin_pay_plus",
    name: "Pay著刷-台新Pay+",
    rate: "3.8%",
    merchants: ["台新Pay+", "日本LAWSON", "BicCamera", "韓國GS25", "DAISO"],
    instruction:
      "台新Pay+綁定支付享3.8%回饋，日韓交易再享免1.5%國外交易手續費。",
    icon: "fa-globe",
    bank: "Taishin",
  },
  {
    id: "taishin_line",
    name: "Pay著刷-LINE Pay/全盈+Pay",
    rate: "2.3%",
    merchants: ["LINE Pay", "全盈+Pay"],
    instruction:
      "LINE Pay及全盈+Pay(2026/7/8起新增)綁定支付享2.3%回饋，四大超商、繳費不在回饋範圍內。",
    icon: "fa-comments",
    bank: "Taishin",
  },
  {
    id: "taishin_daily",
    name: "天天刷",
    rate: "3.3%",
    merchants: [
      "全家 (限台新Pay綁定支付)",
      "7-11 (限台新Pay綁定支付)",
      "萬家福",
      "樂家康",
      "大買家",
      "唐吉訶德",
      "LOPIA",
      "智生活",
      "臺鐵",
      "高鐵",
      "台灣大車隊",
      "LINEGO",
      "Yoxi",
      "Uber",
      "台灣Bolt",
      "中油直營",
      "全國加油",
      "全國特急電",
      "源點EVOASIS",
      "華城電能EVALUE",
      "USPACE",
      "Autopass",
      "車麻吉",
      "寶雅",
      "康是美",
      "屈臣氏",
      "杏一醫療",
      "大樹藥局",
      "丁丁藥局",
      "佑全保健藥妝",
      "健康人生藥局",
    ],
    instruction:
      "日常採買/通勤交通/加油充電/藥妝藥局。全家、7-11限台新Pay綁定支付；智生活為2026/7/8起新增。",
    icon: "fa-basket-shopping",
    bank: "Taishin",
  },
  {
    id: "taishin_big",
    name: "大筆刷",
    rate: "3.3%",
    merchants: [
      "新光三越",
      "skm pay",
      "遠東百貨",
      "遠東SOGO",
      "漢神巨蛋",
      "漢神百貨",
      "漢神洲際",
      "微風",
      "台北101",
      "遠東巨城",
      "廣三SOGO",
      "南紡購物中心",
      "誠品生活",
      "誠品線上",
      "京站",
      "三創生活",
      "夢時代",
      "統一時代",
      "DREAM PLAZA",
      "中友百貨",
      "LaLaport",
      "MITSUI OUTLET PARK",
      "華泰名品城",
      "SKM Park Outlets",
      "IKEA",
      "特力屋",
      "HOLA",
      "宜得利",
      "瑪黑家居",
      "UNIQLO",
      "GU",
      "ZARA",
      "NET",
      "lululemon",
    ],
    instruction: "指定百貨(含誠品生活)/指定Outlet/居家裝修/時尚品味。",
    icon: "fa-bag-shopping",
    bank: "Taishin",
  },
  {
    id: "taishin_dining",
    name: "好饗刷",
    rate: "3.3%",
    merchants: [
      "全臺餐飲",
      "王品瘋Pay",
      "Uber Eats",
      "Foodpanda",
      "拓元售票",
      "KKTIX",
      "年代售票",
      "寬宏售票",
      "OPENTIX兩廳院文化生活",
      "FunNow",
      "錢櫃",
      "好樂迪",
      "ONCOR",
      "sing!go",
      "享溫馨",
      "晶華國際酒店集團",
      "雲朗觀光",
      "台灣萬豪國際集團",
      "煙波國際觀光集團",
      "老爺酒店集團",
      "福華集團",
      "漢來飯店事業群",
      "台北君悅酒店",
      "高雄洲際酒店",
      "臺中勤美洲際酒店",
      "礁溪寒沐酒店",
    ],
    instruction:
      "全臺餐飲/外送平台/購票娛樂/指定KTV/指定飯店。(不含餐券/住宿券)",
    icon: "fa-utensils",
    bank: "Taishin",
  },
  {
    id: "taishin_digital",
    name: "數趣刷",
    rate: "3.3%",
    merchants: [
      "蝦皮 (不含海外直送、黃金等貴金屬、遊戲點數、票券消費)",
      "momo",
      "酷澎",
      "Coupang",
      "PChome (不含商店街、支付連、海外代購、PChome旅遊、儲值、電子票券)",
      "淘寶",
      "Amazon",
      "東森",
      "博客來",
      "Richart Mart",
      "PayEasy",
      "iHerb",
      "SHEIN",
      "Farfetch",
      "Olive Young",
      "知識衛星",
      "Amazing Talker",
      "Tutor ABC",
      "Hahow",
      "PressPlay",
      "MyCard",
      "遊戲橘子",
      "Steam",
      "PlayStation",
      "Nintendo",
      "Netflix",
      "Disney+",
      "ChatGPT",
      "Notion",
      "Canva",
      "Perplexity",
      "Claude",
    ],
    instruction: "網購平台/線上課程/遊戲影音/AI服務。",
    icon: "fa-gamepad",
    bank: "Taishin",
  },
  {
    id: "taishin_travel",
    name: "玩旅刷",
    rate: "3.3%",
    merchants: [
      "海外消費",
      "中華航空",
      "長榮航空",
      "星宇航空",
      "台灣虎航",
      "國泰航空",
      "華信航空",
      "立榮航空",
      "樂桃航空",
      "阿聯酋航空",
      "亞洲航空",
      "酷航",
      "捷星航空",
      "新加坡航空",
      "日本航空",
      "越捷航空",
      "Uber",
      "Grab",
      "SUICA",
      "ICOCA",
      "PASMO",
      "WOWPASS",
      "AIRSIM",
      "Klook",
      "KKday",
      "Agoda",
      "Booking.com",
      "Trip.com",
      "Airbnb",
      "Hotels.com",
      "Expedia",
      "雄獅旅遊",
      "易遊網",
      "東南旅遊",
      "可樂旅遊",
      "長汎假期",
      "五福旅遊",
      "喜鴻假期",
      "易飛旅遊",
      "燦星旅遊",
      "加利利旅行社",
      "鳳凰國際旅行社",
      "山富旅遊",
      "行健旅遊",
    ],
    instruction:
      "海外消費(含實體及線上、歐洲國家交易)/航空公司/海外交通網路/訂房平台/旅行社。",
    icon: "fa-plane",
    bank: "Taishin",
  },
  {
    id: "taishin_holiday",
    name: "假日刷",
    rate: "2%",
    merchants: [],
    instruction: "節假日不限通路(含保費)消費享2%，含LINE Pay及全盈+Pay綁定。",
    icon: "fa-calendar-day",
    bank: "Taishin",
  },
];

const cathayPlans = [
  {
    id: "cathay_formosa_gas",
    name: "台塑家-加油站",
    rate: "2%",
    merchants: ["台塑石油", "台亞", "福懋", "統一速邁樂"],
    instruction:
      "活動期間2026/6/1-2026/12/31。限台塑石油/台亞/福懋/統一速邁樂(限本島)加油站，須以實體CUBE卡或綁定Apple Pay/Samsung Pay/Google Pay/台塑石油Pay/Garmin Pay支付，排除網路交易、儲值卡、電子支付與第三方支付(icash Pay、街口支付、LINE Pay、台灣Pay、悠遊付、OPEN錢包、Pi拍錢包、橘子支付、支付寶等)。",
    icon: "fa-gas-pump",
    bank: "Cathay",
  },
  {
    id: "cathay_formosa_health",
    name: "台塑家-健康生活",
    rate: "2%",
    merchants: ["台塑生醫", "長庚生技", "台塑蔬菜", "台塑購物網"],
    instruction:
      "活動期間2026/6/1-2026/12/31。限台塑生醫/長庚生技/台塑蔬菜實體門市及台塑購物網，回饋以刷卡簽單特約商店名稱認定。",
    icon: "fa-heart-pulse",
    bank: "Cathay",
  },
  {
    id: "cathay_formosa_conv",
    name: "台塑家-指定超商",
    rate: "2%",
    merchants: ["7-11", "全家", "萊爾富"],
    instruction:
      "活動期間2026/6/1-2026/12/31。限7-ELEVEN、全家便利商店、萊爾富實體門市。",
    icon: "fa-store",
    bank: "Cathay",
  },
  {
    id: "cathay_gomypay",
    name: "全支付",
    rate: "2%",
    merchants: [
      "全聯福利中心",
      "大全聯",
      "全支付國內通路",
      "全支付國內合作通路",
    ],
    instruction:
      "活動期間2026/4/22-2026/12/31。須選定「全支付」方案並以全支付綁定CUBE卡刷卡消費。排除繳稅、繳費、跨境支付、儲值(含信用卡/現金/銀行帳戶儲值)、公益捐款、乘車碼、菸酒、代收代售、一歲以下嬰兒奶粉、禮券、福利卡兌換或加贈商品等。",
    icon: "fa-wallet",
    bank: "Cathay",
  },
  {
    id: "cathay_digital",
    name: "玩數位",
    rate: "3%",
    merchants: [
      "ChatGPT",
      "Canva",
      "Claude",
      "Cursor",
      "Duolingo",
      "Gamma",
      "Gemini",
      "Notion",
      "Perplexity",
      "Speak",
      "Apple 媒體服務",
      "Google Play",
      "Disney+",
      "Netflix",
      "Spotify",
      "YouTube Premium",
      "Max",
      "蝦皮購物",
      "momo購物網",
      "PChome 24h購物",
      "小樹購",
      "Coupang酷澎",
      "淘寶",
      "天貓",
    ],
    instruction:
      "活動期間2026/1/1-2026/12/31。AI工具/數位串流/網購平台/國際電商。PChome不含儲值及電子票券；小樹購不含電子票券。",
    icon: "fa-laptop-code",
    bank: "Cathay",
  },
  {
    id: "cathay_shopping_department",
    name: "樂饗購-國內指定百貨",
    rate: "3%",
    merchants: [
      "遠東SOGO",
      "遠東Garden City",
      "新光三越",
      "遠東百貨",
      "台北101",
      "BELLAVITA",
      "微風廣場",
      "統一時代台北店",
      "誠品生活",
      "ATT 4 FUN",
      "京站",
      "美麗華",
      "NOKE忠泰樂生活",
      "大葉高島屋",
      "LaLaport",
      "宏匯廣場",
      "台茂購物中心",
      "大江國際購物中心",
      "Big City遠東巨城購物中心",
      "中友百貨",
      "廣三SOGO",
      "南紡購物中心",
      "耐斯廣場",
      "夢時代",
      "漢神百貨",
      "漢神巨蛋",
      "新月廣場",
      "CITYLINK",
      "秀泰生活",
      "環球購物中心",
      "太平洋百貨",
      "華泰名品城",
      "SKM Park",
      "MITSUI OUTLET PARK",
    ],
    exclusions: ["無印良品", "UNIQLO", "GU", "Gap", "H&M", "ZARA", "lululemon"],
    instruction:
      "回饋以刷卡簽單特店名稱認定，不含店中櫃(如無印良品/UNIQLO/GU/Gap/H&M/ZARA/lululemon等)。統一時代台北店不含DREAM PLAZA。例：台北101的APPLE STORE屬店中櫃，不適用。",
    icon: "fa-bag-shopping",
    bank: "Cathay",
  },
  {
    id: "cathay_shopping_delivery",
    name: "樂饗購-國內外送平台",
    rate: "3%",
    merchants: ["Uber Eats", "foodpanda"],
    instruction: "限選定「樂饗購」權益方案方可獲回饋。",
    icon: "fa-motorcycle",
    bank: "Cathay",
  },
  {
    id: "cathay_shopping_dining",
    name: "樂饗購-國內餐飲",
    rate: "3%",
    merchants: [
      "拉亞漢堡",
      "% Arabica咖啡",
      "黑沃咖啡",
      "SUBWAY",
      "50嵐",
      "麻古茶坊",
      "六扇門時尚湯鍋",
      "八方雲集",
      "麥當勞",
    ],
    instruction:
      "涵蓋透過聯合信用卡中心小額支付平台收費之餐廳(不含餐券)，限選定「樂饗購」方案。每週四單筆滿NT$2,000享加碼5%小樹點優惠券(活動2026/6/1-12/31)，CUBE美食家單月消費滿NT$20,000享指定餐廳10%優惠券。",
    icon: "fa-utensils",
    bank: "Cathay",
  },
  {
    id: "cathay_shopping_drugstore",
    name: "樂饗購-國內藥妝",
    rate: "3%",
    merchants: ["康是美", "屈臣氏"],
    instruction: "限選定「樂饗購」權益方案方可獲回饋。",
    icon: "fa-kit-medical",
    bank: "Cathay",
  },
  {
    id: "cathay_travel_overseas",
    name: "趣旅行-海外實體消費",
    rate: "3%",
    merchants: ["海外實體消費"],
    instruction: "含國外餐飲、飯店到店付款等海外實體交易。",
    icon: "fa-earth-asia",
    bank: "Cathay",
  },
  {
    id: "cathay_travel_japan_park",
    name: "趣旅行-日本指定遊樂園",
    rate: "3%",
    merchants: [
      "東京迪士尼樂園",
      "東京華納兄弟哈利波特影城",
      "大阪環球影城",
      "USJ",
    ],
    instruction: "限日本指定樂園實體消費。",
    icon: "fa-ferris-wheel",
    bank: "Cathay",
  },
  {
    id: "cathay_travel_transport",
    name: "趣旅行-指定國內外交通",
    rate: "3%",
    merchants: [
      "SUICA",
      "PASMO",
      "ICOCA",
      "Uber",
      "Grab",
      "台灣高鐵",
      "yoxi",
      "台灣大車隊",
      "iRent",
      "和運租車",
      "格上租車",
    ],
    instruction:
      "SUICA/PASMO/ICOCA限Apple錢包指定交通卡。國內交通僅限短程叫車服務，不含長租車、機場接送、代駕服務、企業長租、訂閱租賃、中古車租賃。",
    icon: "fa-train",
    bank: "Cathay",
  },
  {
    id: "cathay_travel_airline",
    name: "趣旅行-指定航空公司",
    rate: "3%",
    merchants: [
      "中華航空",
      "長榮航空",
      "星宇航空",
      "台灣虎航",
      "國泰航空",
      "樂桃航空",
      "阿聯酋航空",
      "酷航",
      "捷星航空",
      "日本航空",
      "全日空",
      "亞洲航空",
      "聯合航空",
      "新加坡航空",
      "越捷航空",
      "大韓航空",
      "達美航空",
      "土耳其航空",
      "卡達航空",
      "法國航空",
    ],
    instruction:
      "限航空公司臨櫃、官網或APP購票，不含旅行社/線上旅遊平台/子公司購票。不含機上免稅商品、機場商店、貴賓室、哩程數、套裝行程及哩程折抵之附加費用。",
    icon: "fa-plane",
    bank: "Cathay",
  },
  {
    id: "cathay_travel_hotel",
    name: "趣旅行-指定飯店住宿",
    rate: "3%",
    merchants: ["星野集團", "全球迪士尼飯店", "東橫INN"],
    instruction:
      "限飯店集團臨櫃、官網刷卡訂房，不含旅行社預訂或機+酒/樂園套票；須符合MCC code 3500-3999、7011、7012、7032、7033。",
    icon: "fa-hotel",
    bank: "Cathay",
  },
  {
    id: "cathay_travel_booking",
    name: "趣旅行-指定旅遊/訂房平台",
    rate: "3%",
    merchants: [
      "KKday",
      "Klook",
      "Agoda",
      "Airbnb",
      "Booking.com",
      "Trip.com",
      "ezTravel易遊網",
    ],
    instruction:
      "先訂後付/到店付款可能產生預授權，須於實際扣款當日切換至「趣旅行」；海外平台可能有授權/扣款時間差；選擇到店付款可能改以「飯店住宿」權益計算，不適用訂房平台權益。",
    icon: "fa-bed",
    bank: "Cathay",
  },
  {
    id: "cathay_travel_agency",
    name: "趣旅行-指定旅行社",
    rate: "3%",
    merchants: [
      "雄獅旅遊",
      "可樂旅遊",
      "東南旅遊",
      "五福旅遊",
      "燦星旅遊",
      "山富旅遊",
      "長汎假期",
      "鳳凰旅行社",
      "Ezfly易飛網",
      "理想旅遊",
      "永利旅行社",
      "三賀旅行社",
    ],
    instruction: "限指定旅行社直營門市，不含加盟店、旗下子公司消費。",
    icon: "fa-suitcase-rolling",
    bank: "Cathay",
  },
  {
    id: "cathay_select",
    name: "集精選",
    rate: "2%",
    merchants: [
      "U-POWER",
      "EVOASIS",
      "EVALUE",
      "TAIL",
      "iCharging",
      "車麻吉",
      "uTagGo",
      "家樂福",
      "LOPIA",
      "全聯福利中心",
      "台灣中油",
      "7-11",
      "全家",
      "IKEA",
    ],
    instruction:
      "充電站含綠界/藍新支付平台交易。車麻吉不含加油、充電；uTagGo不含月租停車。全聯限實體門市，不含大全聯(大全聯適用「全支付」方案)。台灣中油限直營站。",
    icon: "fa-charging-station",
    bank: "Cathay",
  },
  {
    id: "cathay_birthday_10",
    name: "慶生月-指定餐飲10%",
    rate: "10%",
    merchants: [
      // 台中美食
      "火火燒肉販賣所",
      "澄居烤物燒肉",
      "鳥苑 Torien Yakitori",
      "豐生茶館梅川東店",
      "做茶菜",
      "Sozai",
      "稻鎮經典台灣菜",
      "所 SUO",
      "嵩 sung",
      "JAI 宅",
      // 中西日料理/微醺
      "Another Eatery",
      "The other Eatery中山小酒館",
      "輝室",
      "鯡魚工作室",
      "三點三",
      "粥起粥底火鍋熱炒",
      "你家樓下",
      "銀杏中餐廳",
      "Ashin 阿鑫",
      "京丘炭火燒鳥專門店",
      "京丘燒鳥酒処",
      "燒鳩",
      "朧板前燒肉",
      "久碳吉炭火燒肉",
      "小方舟串燒酒場",
      "毛丼丼飯專門店",
      "毛房蔥柚鍋．冷藏肉專門",
      "毛蔬亞洲蔬食",
      // 在地食材
      "KOMBOI",
      "好嶼 HOSU",
      "肉料理福",
      "澀 Sur-",
      // 連鎖燒肉鍋物甜點
      "UNCLE SHAWN 燒肉餐酒館",
      "竣師父牛肉麵",
      "UNCLE RAY串燒·牛飲·咖喱",
      "陳阿姨火鍋灶咖",
      "蜀叔麻辣鍋",
      "Pastaio",
      "Pastaio noodle cafe",
      "青沐",
      "芮秋 Rachel",
      "立秋 Li Chiu",
      "祇園.禪院壽喜燒",
      "二本松涮涮屋",
      "橋山壽喜燒",
      "春囍打邊爐",
      "有你真好湘菜沙龍",
      "水鳥和洋創作料理",
      "髙 GAO Taipei",
      "法國的秘密甜點",
      "creammm.t",
      "AUFGLET",
      "Fake Sober",
      "Sober Bakery",
      "Sober & Burger",
      // 日本樂園/娛樂
      "東京迪士尼樂園",
      "大阪環球影城",
      "USJ",
      "PlayStation",
      "Nintendo",
      "巴哈姆特動畫瘋",
      "錢櫃KTV",
      "好樂迪KTV",
      "星聚點KTV",
      "享溫馨KTV",
    ],
    instruction:
      "活動期間2026/7/1-9/30，生日當月限定(需切換權益)。回饋以刷卡簽單特店名稱認定，不適用設立於百貨/飯店/商場內之實體門市，不適用透過inline刷卡消費支付。",
    icon: "fa-cake-candles",
    bank: "Cathay",
  },
  {
    id: "cathay_birthday_35",
    name: "慶生月-指定消費3.5%",
    rate: "3.5%",
    merchants: ["新光三越", "Uber Eats", "Klook", "FunNow"],
    exclusions: ["SKM Park Outlets 高雄草衙"],
    instruction:
      "活動期間2026/7/1-9/30，生日當月限定(需切換權益)。新光三越不含SKM Park Outlets高雄草衙。",
    icon: "fa-gift",
    bank: "Cathay",
  },
  {
    id: "cathay_kids_insurance",
    name: "童樂匯-保費",
    rate: "1%",
    merchants: ["國內壽險保費", "國內產險保費"],
    instruction:
      "需先解鎖童樂匯權益(2026/7/1-11/20，須客戶與未成年子女皆持有本行帳戶且客戶持有效CUBE卡正卡)。保費0利率分期不列入回饋；第三方支付(街口/LINE Pay/Pi錢包/歐付寶)繳保費不適用；不含躉繳保費、投資型及利率變動型年金保費、團體保險自費件、2021/6底前傳統保單續期保費。",
    icon: "fa-file-shield",
    bank: "Cathay",
  },
  {
    id: "cathay_kids_tuition",
    name: "童樂匯-指定私校學費",
    rate: "1%",
    merchants: [
      "台北美國學校",
      "台北歐洲學校",
      "道明外僑學校",
      "馬禮遜學校",
      "康乃薾美國學校",
      "立人國際國小",
      "康橋國際學校",
      "華盛頓小學",
      "復興實驗高中",
      "維多利亞雙語中小學",
      "高雄美國學校",
    ],
    instruction:
      "需解鎖童樂匯權益。僅限透過i繳費平台繳學費；台北歐洲學校須先透過TES AOS入口跳轉至i繳費完成繳費。",
    icon: "fa-graduation-cap",
    bank: "Cathay",
  },
  {
    id: "cathay_kids_restaurant",
    name: "童樂匯-親子餐廳",
    rate: "5%",
    merchants: [
      "台灣壽司郎",
      "雞湯大叔",
      "陶板屋",
      "YAYOI彌生軒",
      "大戶屋",
      "甲蟲秘境",
      "大樹先生的家",
      "Money Jump媽妳講親子餐廳",
      "小島3.5度親子餐廳",
    ],
    instruction:
      "需解鎖童樂匯權益。陶板屋限使用王品瘋Pay結帳；YAYOI彌生軒限街邊店；不適用設立於百貨/飯店/商場內之實體門市。",
    icon: "fa-bowl-food",
    bank: "Cathay",
  },
  {
    id: "cathay_kids_entertainment",
    name: "童樂匯-親子育樂",
    rate: "5%",
    merchants: [
      "Klook",
      "東京迪士尼樂園",
      "大阪環球影城",
      "USJ",
      "麗寶樂園",
      "六福村主題樂園",
      "九族文化村",
      "劍湖山世界主題樂園",
      "義大遊樂世界",
      "小叮噹科學園區主題樂園",
      "Xpark",
      "巧虎夢想樂園",
    ],
    instruction:
      "需解鎖童樂匯權益。遊樂園限現場或官網購票，不含旅行社/線上旅遊平台購票；Xpark限館內人工結帳櫃台消費，不適用線上購票及自動售票機。",
    icon: "fa-ferris-wheel",
    bank: "Cathay",
  },
  {
    id: "cathay_kids_hotel",
    name: "童樂匯-親子飯店",
    rate: "5%",
    merchants: [
      "台北喜來登大飯店",
      "蘭城晶英酒店",
      "台南晶英酒店",
      "礁溪寒沐酒店",
      "大溪笠復威斯汀度假酒店",
      "煙波大飯店新竹湖濱館",
      "麗寶福容大飯店",
      "雲品溫泉酒店",
      "和逸飯店",
      "義大皇家酒店",
      "高雄萬豪酒店",
      "墾丁凱撒大飯店",
      "花蓮遠雄悅來大飯店",
      "瑞穗天合國際觀光酒店",
      "六福莊",
      "宜蘭礁溪鳳凰酒店",
      "桃園名人堂花園大飯店",
    ],
    instruction:
      "需解鎖童樂匯權益。限直接透過飯店官網訂購住宿，不適用旅行社或其他訂房平台；不含婚宴方案、館內附設餐廳、outlet等消費。",
    icon: "fa-hotel",
    bank: "Cathay",
  },
  {
    id: "cathay_kids_baby",
    name: "童樂匯-母嬰用品店",
    rate: "5%",
    merchants: [
      "卡多摩嬰童館",
      "媽咪愛",
      "樂兒屋",
      "寶齡婦幼館",
      "步步樂BuBuLuv",
      "安琪兒婦嬰百貨",
      "宜兒樂",
      "麗兒采家",
      "Taobaby濤寶日記",
      "俏媽咪",
      "媽媽好",
    ],
    instruction:
      "需解鎖童樂匯權益。不適用設立於百貨/飯店/商場內之實體門市；一歲以下嬰幼兒奶粉及藥品不適用。",
    icon: "fa-baby",
    bank: "Cathay",
  },
  {
    id: "cathay_kids_course",
    name: "童樂匯-五感體驗課",
    rate: "10%",
    merchants: [
      "朱宗慶打擊樂教學系統",
      "雲門舞集舞蹈教室",
      "Yamaha音樂教室",
      "TutorABC Junior",
      "Etalking Kids",
      "iSKI滑雪俱樂部",
      "汐游寶寶",
      "風城游汐谷",
    ],
    instruction:
      "需解鎖童樂匯權益。限教學課程購買，不含展演門票、贊助捐款、教材教具租借、場地租借。Yamaha限台灣直營門市及揚昇石牌音樂教室；朱宗慶排除台北古亭/板橋中山/台北林口/新竹竹北教室。",
    icon: "fa-music",
    bank: "Cathay",
  },
  {
    id: "cathay_kids_brand",
    name: "童樂匯-嬰幼童品牌官網",
    rate: "10%",
    merchants: [
      "10mois",
      "Mamas&Papas",
      "古北町",
      "Little Wonders",
      "Seahorse Originals",
    ],
    instruction:
      "需解鎖童樂匯權益。僅限台灣官網消費，不含百貨商場內(如百貨公司、家樂福、車站商場、機場美食街)設立之店家；含透過綠界支付平台交易。",
    icon: "fa-shirt",
    bank: "Cathay",
  },
];

const yushanPlans = [
  {
    id: "yushan_mobile_pay",
    name: "行動支付",
    rate: "最高4.5%",
    merchants: [
      "玉山Wallet電子支付",
      "LINE Pay",
      "全支付",
      "街口支付",
      "悠遊付",
      "全盈+PAY",
      "iPASS MONEY",
      "icash Pay",
      "支付寶",
    ],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限指定電子支付綁定玉山Unicard刷卡消費，排除超商、全聯、稅費。LINE Pay須有指定請款名稱且保費不列入。玉山Wallet限國內TWQR/台灣Pay(排除PayPay、學費、代扣繳)。支付寶為新增支付通路。",
    icon: "fa-mobile-screen",
    bank: "Yushan",
  },
  {
    id: "yushan_ec",
    name: "電商平台",
    rate: "最高4.5%",
    merchants: ["momo購物網", "蝦皮購物", "淘寶網", "Coupang酷澎"],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限實體卡/Apple Pay/Google Pay/Samsung Pay，第三方支付(如LINE Pay、街口)另計不適用本方案。蝦皮不含跨境。momo含富盛旅行社。Coupang含火箭速配/跨境服務。",
    icon: "fa-cart-shopping",
    bank: "Yushan",
  },
  {
    id: "yushan_department_store",
    name: "國內百貨",
    rate: "最高4.5%",
    merchants: [
      "新光三越百貨",
      "SKM Park Outlets 高雄草衙",
      "遠東SOGO",
      "遠東Garden City",
      "台北101",
      "華泰名品城",
      "三井OUTLET",
      "秀泰生活",
      "LaLaport",
      "Big City遠東巨城購物中心",
      "昇恆昌",
      "統一時代百貨",
      "DREAM PLAZA",
      "遠東百貨",
      "Global Mall環球購物中心",
      "漢神百貨",
      "台中漢神洲際購物廣場",
      "微風百貨",
      "誠品生活",
      "誠品書店",
      "誠品線上",
    ],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限實體卡/Apple Pay/Google Pay/Samsung Pay，回饋以簽單特店名稱認定，百貨內店中獨立店(如Apple直營)不計入。新光三越含SKM Park Outlets高雄草衙；漢神百貨不含漢神巨蛋；誠品生活含誠品書店與誠品線上；統一時代百貨含DREAM PLAZA。",
    icon: "fa-bag-shopping",
    bank: "Yushan",
  },
  {
    id: "yushan_lifestyle",
    name: "生活採買",
    rate: "最高4.5%",
    merchants: [
      "萬家福",
      "樂家康",
      "屈臣氏",
      "康是美",
      "特力屋",
      "HOLA",
      "hoi好好生活",
      "UNIQLO",
      "NET",
      "杏一藥局",
      "卡多摩",
    ],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限實體卡/Apple Pay/Google Pay/Samsung Pay，僅限國內特約門市/官網/APP。UNIQLO、NET僅限街邊獨立店，百貨商場店中店不適用。",
    icon: "fa-basket-shopping",
    bank: "Yushan",
  },
  {
    id: "yushan_dining",
    name: "餐飲美食",
    rate: "最高4.5%",
    merchants: ["Uber Eats", "foodpanda", "王品瘋Pay"],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限實體卡/Apple Pay/Google Pay/Samsung Pay。王品瘋Pay限使用App瘋Pay功能綁定玉山Unicard支付餐點方適用。",
    icon: "fa-utensils",
    bank: "Yushan",
  },
  {
    id: "yushan_traffic",
    name: "加油交通",
    rate: "最高4.5%",
    merchants: [
      "台灣中油",
      "台塑石油PAY",
      "55688",
      "台灣大車隊",
      "機場接送",
      "台鐵",
      "高鐵",
      "Uber",
    ],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限實體卡/Apple Pay/Google Pay/Samsung Pay。台灣中油限直營站；台塑石油依官方APP服務據點；台鐵/高鐵限官網、APP、現場購票(排除旅行社代購、超商)；Uber限國內新臺幣交易。",
    icon: "fa-car",
    bank: "Yushan",
  },
  {
    id: "yushan_travel",
    name: "航空旅遊",
    rate: "最高4.5%",
    merchants: [
      "中華航空",
      "長榮航空",
      "日本航空",
      "台灣虎航",
      "樂桃航空",
      "酷航",
      "Trip.com",
      "Booking.com",
      "Hotels.com",
      "Expedia",
      "KKday",
      "Klook",
      "雄獅旅遊",
      "可樂旅遊",
      "東南旅遊",
      "Agoda",
      "五福旅遊",
      "加利利旅行社",
      "找到了旅行社",
      "喜鴻假期",
      "鳳凰旅遊",
    ],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限實體卡/Apple Pay/Google Pay/Samsung Pay。航空公司限官網、APP、臨櫃購票；訂房平台須線上完成付款(排除到店付款)。Klook限國內新臺幣交易；找到了旅行社分期交易不適用。",
    icon: "fa-plane",
    bank: "Yushan",
  },
  {
    id: "yushan_overseas",
    name: "國外實體",
    rate: "最高4.5%",
    merchants: [
      "日本",
      "韓國",
      "泰國",
      "越南",
      "新加坡",
      "馬來西亞",
      "菲律賓",
      "中國",
      "香港",
      "澳門",
      "美國",
      "加拿大",
      "英國",
      "法國",
      "德國",
      "義大利",
      "澳洲",
      "紐西蘭",
    ],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限實體卡/Apple Pay/Google Pay/Samsung Pay，限面對面實體交易，排除網路交易、幣別為台幣或消費地點在台灣之交易，關島不列入美國認列，金額不含手續費，不含服務費、預借現金與賭場提款。",
    icon: "fa-globe",
    bank: "Yushan",
  },
  {
    id: "yushan_selected",
    name: "精選商家",
    rate: "最高4.5%",
    merchants: [
      "Apple直營店",
      "小米台灣",
      "全國電子",
      "燦坤",
      "拓元售票",
      "威秀影城",
      "國賓影城",
      "新光影城",
      "錢櫃KTV",
    ],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限實體卡/Apple Pay/Google Pay/Samsung Pay。Apple限台灣直營店與線上商城；小米限官網、小米之家與專賣店；影城限現場及網路訂票。",
    icon: "fa-store",
    bank: "Yushan",
  },
  {
    id: "yushan_esg",
    name: "ESG消費",
    rate: "最高4.5%",
    merchants: [
      "玉山Wallet愛心捐款",
      "特斯拉",
      "Tesla",
      "弘道老人福利基金會",
      "華山社會福利慈善事業基金會",
      "伊甸社會福利基金會",
      "喜憨兒社會福利基金會",
      "社團法人中華民國保護動物協會",
      "勵馨社會福利事業基金會",
      "財團法人私立天主教中華聖母社會福利慈善事業基金會",
      "財團法人羅慧夫顱顏基金會",
      "社團法人臺灣雷特氏症病友關懷協會",
      "財團法人陽光社會福利基金會",
      "社團法人台灣微客公益行動協會",
      "財團法人台北市失親兒福利基金會",
      "社團法人中華民國失智者照顧協會",
      "財團法人台北市私立雙連視障關懷基金會",
      "社團法人台灣同伴動物扶助協會",
      "社團法人台灣懷生相信動物協會",
      "財團法人普仁青年關懷基金會",
      "社團法人中華民國荒野保護協會",
      "社團法人台灣之心愛護動物協會",
    ],
    instruction:
      "適用期間2026/7/1-2026/12/31。UP方案最高4.5%。限實體卡/Apple Pay/Google Pay/Samsung Pay。捐款限透過玉山Wallet愛心捐款專區(單筆捐款/定期定額)刷卡交易。",
    icon: "fa-seedling",
    bank: "Yushan",
  },
];
